download:
  user: 'root'
  host: 'devtia.com'
  database:
    directory: '%kernel.root_dir%/../var/backups/databases'
    only_structure:
      - 'content_post_history'

    remote:
      host: 'localhost'
      name: 'devtia'
      user: 'root'
      password: 'venti140raS;'

    local:
      host: '%database_host%'
      name: '%database_name%'
      user: '%database_user%'
      password: '%database_password%'

  directories:

    web_uploads:
      remote: '/var/www/devtia.com/shared/web/uploads'
      local: '%kernel.root_dir%/../web'
      exclude:
        - 'cache'

    var_data:
      remote: '/var/www/devtia.com/shared/var/data/file/*'
      local: '%kernel.root_dir%/../var/data/file'