doctrine_migrations:
  dir_name: "%kernel.root_dir%/Resources/migrations"
  namespace: 'Migration'
  table_name: 'migration_versions'
  name: 'Application Migrations'
  organize_migrations: 'BY_YEAR_AND_MONTH'