vich_uploader:
  db_driver: orm
  mappings:
    image:
      uri_prefix: '%app.web_upload_path%'
      upload_destination: '%app.upload_dir%'
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
      namer: 'vich_uploader.namer_hash'
      directory_namer: 'core.service_vich.directory_namer'

    file:
      upload_destination: '%app.data_dir%/file'
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
      namer: 'vich_uploader.namer_hash'
      directory_namer: 'core.service_vich.directory_namer'